### ISSUE TITLE
Callback.js response not interpreted correctly by browser

### ISSUE THREAD

**Issue by kerryhatcher** [i40west/netlify-cms-cloudflare-pages#1]
The auth process appears to work up until the call back function is called. Its like the browser is treating the response from the function as string text instead of HTML. I tried updating the html to include the full html, head, body tags but that didn't have any effect. The response gets wrapped in a <pre> tag and rendered as plain text in the browser. I've tried in Chrome and Firefox. I'm sure I'm just missing something here but I've tried going though the setup several times now with same result. 

![image](https://user-images.githubusercontent.com/1011814/188900566-4fd64674-27c7-4689-a7f3-0e2b2823167f.png)

**Comment by i40west** [comment]
Are you doing anything to add or modify HTTP response headers? Having the response wrapped in `<pre>` tags happens when the browser considers the response `text/plain`. Your screenshot doesn't include all the response headers, so if you could show all HTTP response headers that would be helpful.
